CREATE TABLE IF NOT EXISTS lab_settings (
  id INT PRIMARY KEY NOT NULL,
  lab_config TEXT,
  appreciation_config TEXT,
  checkin_config TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;